# integrator/src/main/resources/application.yml

server:
  port: 8085

spring:
  application:
    name: integrator

# gRPC Client Configuration - FIXED
grpc:
  client:
    emergency-service:
      address: static://emergency-grpc:9090  # Changed from localhost to emergency-grpc
      negotiationType: plaintext

# GraphQL Service
graphql:
  service:
    url: http://query-graphql:8084/graphql  # Already correct

logging:
  level:
    com.smartcity: DEBUG
    io.grpc: DEBUG